# .prettierrc.toml

# Adapted from https://github.com/typescript-eslint/typescript-eslint/.prettierrc.json
arrowParens = "avoid"
bracketSameLine = false
bracketSpacing = true
endOfLine = "lf"
jsxSingleQuote = false
printWidth = 105
proseWrap = "preserve"
quoteProps = "as-needed"
semi = true
singleQuote = true
tabWidth = 2
trailingComma = "all"
useTabs = false

# START Solidity files config
# From https://github.com/prettier-solidity/prettier-plugin-solidity#readme
[[overrides]]
files = "*.sol"
[overrides.options]
bracketSpacing = false
printWidth = 105
singleQuote = false
tabWidth = 4
useTabs = false
# END Solidity files config
